# Generated by Django 2.2.14 on 2022-07-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220708_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiring',
            name='name',
        ),
    ]
