# Generated by Django 2.2.14 on 2022-07-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_hiring_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='image',
            field=models.ImageField(default=1, upload_to='media/professional_images'),
            preserve_default=False,
        ),
    ]
