# Generated by Django 2.2.14 on 2022-07-13 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_professional_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('story', models.TextField()),
                ('image', models.ImageField(upload_to='media/news_images')),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
                ('posted_by', models.CharField(max_length=100)),
            ],
        ),
    ]
